### ISSUE TITLE
Every machine in Informatics is a prefix of inf.ed.ac.uk

### ISSUE THREAD

**Issue by qaisjp** [dylan-thinnes/domainatrix#22]
- Here's a list of machines in Appleton Tower: https://map.betterinformatics.com/api/rooms/3-robotics,3.05,3.09,4.05,4.07,4.09,4.12,4.14,4.14a,5.02,5.03,5.04,5.05,5.07,5.08,6.06,7.01

**Comment by dylan-thinnes** [comment]
Sweet! I'll add it in the new update.
How'd you get ahold of these domain names?

**Comment by qaisjp** [comment]
We walked around the building

**Comment by dylan-thinnes** [comment]
Fair enough 🙂
